import type { AppSnapshot } from "../types";

export function snapshotFixture(now = Date.now()): AppSnapshot {
  return {
    settings: {
      schemaVersion: 14,
      listeningSource: {
        executablePath: "C:\\Games\\MistfallHunter-Win64-Shipping.exe",
        executableName: "MistfallHunter-Win64-Shipping.exe",
        displayName: "Mistfall Hunter",
        lastPid: 4242,
      },
      captureMode: "process_tree",
      outputDeviceId: "Speakers (PRO)",
      rescueScanEnabled: false,
      autoAttach: true,
      hotkeys: {
        toggleListening: "F8",
        pushToTalk: "F9",
        copyLatest: "F10",
        editOverlay: "F7",
      },
      overlay: {
        opacity: 0.94,
        fontScale: 1,
        fadeSeconds: 8,
        maxItems: 4,
        width: 420,
        height: 236,
      },
      vad: {
        processTree: { vadThreshold: 0.5, gainDb: 0 },
        systemOutput: { vadThreshold: 0.35, gainDb: 9 },
        silenceMs: 500,
        preRollMs: 200,
        maxUtteranceMs: 12000,
      },
      installationId: "00000000-0000-4000-8000-000000000001",
      glossary: [{ source: "Mistfall", target: "Mistfall" }],
    },
    runtime: {
      listening: true,
      microphoneActive: false,
      overlayEditMode: false,
      workerReady: true,
      workerModel: "silero-vad",
      aiSttBusy: false,
      aiStatus: "บริการ AI พร้อมใช้งาน",
      aiService: { state: "ready", message: "บริการ AI พร้อมใช้งาน", incomingModel: "whisper-large-v3-turbo", microphoneModel: "whisper-large-v3-turbo", translationModel: "server-configured-model", retryAfterMs: null },
      attachedSource: {
        pid: 4242,
        name: "MistfallHunter-Win64-Shipping.exe",
        executablePath: "C:\\Games\\MistfallHunter-Win64-Shipping.exe",
        displayName: "Mistfall Hunter",
        isMistfall: true,
      },
      effectiveCapturePid: 4000,
      effectiveCaptureName: "MistfallHunter.exe",
      effectiveOutputDeviceId: undefined,
      effectiveOutputDeviceName: undefined,
      effectiveOutputDeviceIsDefault: false,
      audioRmsDbfs: -28,
      audioPeakDbfs: -10,
      audioLastSeenAtMs: now,
      vadActive: false,
      effectiveVadThreshold: 0.5,
      effectiveVadGainDb: 0,
      effectiveVadAutoGainDb: 0,
      droppedAudioChunks: 0,
      statusMessage: "กำลังฟัง Mistfall Hunter",
    },
    history: [
      {
        segmentId: "incoming-1",
        stream: "incoming",
        sourceDisplayName: "Mistfall Hunter",
        originalLanguage: "en",
        originalText: "Join us at the north gate.",
        translatedText: "ไปรวมกันที่ประตูเหนือ",
        status: "success",
        createdAtMs: now - 500,
      },
      {
        segmentId: "mic-1",
        stream: "microphone",
        originalLanguage: "th",
        originalText: "กำลังไป",
        translatedText: "On my way.",
        status: "success",
        createdAtMs: now - 1_000,
      },
    ],
  };
}
